### ISSUE TITLE
is this still working

### ISSUE THREAD

**Issue by itrustgod** [abcnews/data-life#4] opened 2019-02-12 20:43 UTC
im looking to have mitmproxy capture traffic from my phone which i have openvpn installed on but i cant seem to get this working anyone who has been able to successfully install this and get this working im willing to pay you to have this done for me please....

**Comment by drzax** [comment] 2019-02-13 00:13
This should still work as described in the various readme files, but it doesn't use Open VPN, it uses IPSec. Assuming you're using iOS you would need to install a profile to enable the VPN. You can find instructions and a template in [the readme](https://github.com/abcnews/data-life/blob/master/server/README.md). 

I'm going to close this as it's not a bug. Unfortunately, we're not in a position to provide any further support.

**Closed as completed by drzax** 2019-02-13 00:13 UTC
